[theme]
base="light"
primaryColor="#33b5e5"             # A brighter light blue
backgroundColor="#ffffff"          # Keep white for clarity
secondaryBackgroundColor="#e6f4fb" # Very light blue background for panels
textColor="#1c2b33"                # Slightly softer black
font="sans serif"
