[theme]
base="dark"
primaryColor="#ff6ec7"             # Electric pink
backgroundColor="#0f0f0f"          # Deep black for contrast
secondaryBackgroundColor="#1f1f3a" # Dark purple-blue for panels
textColor="#f8f8ff"                # Ghost white for clarity
font="monospace"                   # Fun + techy (you can also try 'serif' for a whimsical feel)
